name: Markdown

on: [push, pull_request]

jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out files from GitHub
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Installing dependencies
        run: npm install
        env:
          CI: true
      - name: Running remark lint
        run: npm run markdown:lint
